import { Inter } from "next/font/google";
import Header from "@/component/Header";
import "../style/app.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer>Nhựt Trường học Nextjs basic</footer>
      </body>
    </html>
  );
}
